import { PrismaClient } from "@prisma/client"
import { config } from "dotenv"

config({ path: ".env.local" })

const prisma = new PrismaClient()

const accounts = [
  // traders
  { handle: "plur_daddy", displayName: "plur daddy", category: "traders" as const },
  { handle: "TraderNoah", displayName: "Noah", category: "traders" as const },
  { handle: "lBattleRhino", displayName: "Rhino", category: "traders" as const },
  { handle: "HsakaTrades", displayName: "Hsaka", category: "traders" as const },
  { handle: "Pickle_cRypto", displayName: "pickle", category: "traders" as const },
  { handle: "Bluntz_Capital", displayName: "Bluntz", category: "traders" as const },
  { handle: "mel_8686", displayName: "Mel", category: "traders" as const },
  { handle: "avotoast", displayName: "Avocado Toast", category: "traders" as const },
  { handle: "0xMerp", displayName: "merp", category: "traders" as const },
  { handle: "thoughtfultrade", displayName: "clairvoyant", category: "traders" as const },
  { handle: "notwashed", displayName: "washed", category: "traders" as const },
  { handle: "gammichan", displayName: "Gammichan", category: "traders" as const },
  { handle: "c2mtrading", displayName: "C2M", category: "traders" as const },
  { handle: "slipsliderr", displayName: "Puffy", category: "traders" as const },
  { handle: "0xn4te", displayName: "NATE", category: "traders" as const },
  { handle: "lightcrypto", displayName: "light", category: "traders" as const },
  { handle: "DonAlt", displayName: "DonAlt", category: "traders" as const },
  { handle: "crymeaCOIN", displayName: "pc", category: "traders" as const },
  { handle: "moneywithcarter", displayName: "Carter", category: "traders" as const },
  { handle: "koningkarell", displayName: "Koning", category: "traders" as const },
  { handle: "0xPajke", displayName: "Pajke", category: "traders" as const },
  { handle: "__bleeker", displayName: "bleeker", category: "traders" as const },
  { handle: "ReetikaTrades", displayName: "Reetika", category: "traders" as const },
  { handle: "stoicsavage", displayName: "sto", category: "traders" as const },
  { handle: "docXBT", displayName: "Doc", category: "traders" as const },
  { handle: "Tradermayne", displayName: "Mayne", category: "traders" as const },
  { handle: "cointradernik", displayName: "Nik", category: "traders" as const },
  { handle: "22loops", displayName: "Looposhi", category: "traders" as const },
  { handle: "CryptoParadyme", displayName: "Dyme", category: "traders" as const },
  { handle: "ImTrizzy", displayName: "Trizzy", category: "traders" as const },
  { handle: "buyerofponzi", displayName: "Ponzi Trader", category: "traders" as const },
  { handle: "owen1v9", displayName: "owen", category: "traders" as const },
  { handle: "blknoiz06", displayName: "Ansem", category: "traders" as const },
  { handle: "filthy555", displayName: "filthy", category: "traders" as const },
  { handle: "d_gilz", displayName: "David", category: "traders" as const },
  { handle: "Ritesh_Trades", displayName: "Ritesh", category: "traders" as const },
  { handle: "c0xswain", displayName: "ML", category: "traders" as const },
  { handle: "Rob100x", displayName: "Rob", category: "traders" as const },
  { handle: "RiffRaffOz", displayName: "RiffRaff", category: "traders" as const },
  { handle: "Crypto_Chase", displayName: "Crypto Chase", category: "traders" as const },
  { handle: "0xuberM", displayName: "uberM", category: "traders" as const },
  { handle: "astaso1", displayName: "asta", category: "traders" as const },
  { handle: "xauchasing", displayName: "xauChasing", category: "traders" as const },
  { handle: "iamnotmagi", displayName: "Magi", category: "traders" as const },
  { handle: "Redactedpupil", displayName: "boop", category: "traders" as const },
  { handle: "ryzzqq", displayName: "Risk", category: "traders" as const },
  { handle: "azardotwtf", displayName: "Azar", category: "traders" as const },
  { handle: "BigTrout300", displayName: "BigTrout", category: "traders" as const },
  { handle: "DipWheeler", displayName: "Dip Wheeler", category: "traders" as const },
  { handle: "ibuyrugs", displayName: "ibuyrugs", category: "traders" as const },
  { handle: "Cassh0rt", displayName: "Cassh0rt", category: "traders" as const },
  { handle: "Cheshire_Cap", displayName: "Cheshire Capital", category: "traders" as const },
  { handle: "0xSunRun", displayName: "SunRun", category: "traders" as const },
  { handle: "issathecooker", displayName: "Issa", category: "traders" as const },
  { handle: "soulessmetanoia", displayName: "souless", category: "traders" as const },
  { handle: "retro", displayName: "retro", category: "traders" as const },
  { handle: "real_y22", displayName: "Y22", category: "traders" as const },
  { handle: "onevsnine", displayName: "1v9", category: "traders" as const },
  { handle: "The_Airmass", displayName: "Airmass", category: "traders" as const },
  { handle: "effervescence_o", displayName: "effervescence", category: "traders" as const },
  { handle: "bagsheera", displayName: "bags", category: "traders" as const },
  { handle: "sized_in", displayName: "sized in", category: "traders" as const },
  { handle: "Parida", displayName: "Parida", category: "traders" as const },
  { handle: "goosexyz_", displayName: "Goose", category: "traders" as const },
  { handle: "PlutonicXBT", displayName: "Snorlax", category: "traders" as const },
  { handle: "ieaturfoods", displayName: "ieaturfood", category: "traders" as const },
  { handle: "bendoverxbt", displayName: "Ben Dover", category: "traders" as const },
  { handle: "Erasing_Light", displayName: "Dystopia", category: "traders" as const },
  { handle: "insomniacxbt", displayName: "insomniac", category: "traders" as const },
  { handle: "CavanXy", displayName: "Cav", category: "traders" as const },
  { handle: "QuantMeta", displayName: "Metaquant", category: "traders" as const },
  { handle: "stogolp", displayName: "sgp", category: "traders" as const },
  { handle: "Web3Quant", displayName: "W3Q", category: "traders" as const },
  { handle: "0xMentalIllness", displayName: "Dumpelstiltskin", category: "traders" as const },
  { handle: "munchPRMR", displayName: "munch", category: "traders" as const },
  { handle: "0xLawliette", displayName: "L", category: "traders" as const },
  { handle: "0xfhd_", displayName: "fhd", category: "traders" as const },
  { handle: "MWCunfiltered", displayName: "MWCunfiltered", category: "traders" as const },
  { handle: "GCRClassic", displayName: "GCR", category: "traders" as const },
  { handle: "chumbawamba22", displayName: "Chumbawamba", category: "traders" as const },
  { handle: "honey_xbt", displayName: "Honey", category: "traders" as const },
  { handle: "yeezytwts", displayName: "yeezy", category: "traders" as const },
  { handle: "GiganticRebirth", displayName: "GCR (journal)", category: "traders" as const },
  { handle: "conzimp", displayName: "Ansem (journal)", category: "traders" as const },
  { handle: "spyzer", displayName: "spyzer", category: "traders" as const },
  { handle: "awawat", displayName: "Awawat", category: "traders" as const },
  { handle: "cryptojamie7", displayName: "CryptoJamie", category: "traders" as const },
  { handle: "blockgraze", displayName: "blockgraze", category: "traders" as const },
  { handle: "comfortablylong", displayName: "spiro", category: "traders" as const },
  { handle: "PaikCapital", displayName: "hdf", category: "traders" as const },
  { handle: "Juicycooks", displayName: "juicy", category: "traders" as const },
  { handle: "kelxyz_", displayName: "kel", category: "traders" as const },
  { handle: "TruckPump", displayName: "Pump Truck", category: "traders" as const },
  { handle: "Pentosh1", displayName: "Pentoshi", category: "traders" as const },
  { handle: "skytrades8", displayName: "Sky", category: "traders" as const },
  { handle: "CL207", displayName: "CL", category: "traders" as const },
  { handle: "dogoshii", displayName: "dogo was here", category: "traders" as const },
  { handle: "degentradingLSD", displayName: "degentrading", category: "traders" as const },
  { handle: "mustached0", displayName: "mustached0", category: "traders" as const },
  { handle: "youngtilopa", displayName: "tilopa", category: "traders" as const },
  { handle: "coin_casanova", displayName: "casa", category: "traders" as const },
  { handle: "levels_crypto", displayName: "levels", category: "traders" as const },
  { handle: "monkmoneymm", displayName: "Monk", category: "traders" as const },
  { handle: "TheCryptoNexus", displayName: "Nexus", category: "traders" as const },
  { handle: "tetra_gamma", displayName: "tetra gamma", category: "traders" as const },
  { handle: "rodeo_crypro", displayName: "Rodeo", category: "traders" as const },
  { handle: "2211x0", displayName: "stun", category: "traders" as const },
  { handle: "whodoneit21", displayName: "whodoneit21", category: "traders" as const },
  { handle: "Erebos991", displayName: "Erebos", category: "traders" as const },
  { handle: "0xSisyphus", displayName: "Sisyphus", category: "traders" as const },
  { handle: "intuitio_", displayName: "intuitio", category: "traders" as const },
  { handle: "smileycapital", displayName: ":)", category: "traders" as const },
  { handle: "punter_punts", displayName: "punter", category: "traders" as const },
  { handle: "Opaque1555", displayName: "Opaque", category: "traders" as const },
  { handle: "0xfattyfrog", displayName: "fattyfrog", category: "traders" as const },
  { handle: "pikathegoat", displayName: "pika", category: "traders" as const },
  { handle: "game_for_one", displayName: "Game", category: "traders" as const },
  { handle: "apewoodx", displayName: "apewood", category: "traders" as const },
  { handle: "Nstr_tj", displayName: "tj", category: "traders" as const },
  { handle: "profitmaxxing", displayName: "magi", category: "traders" as const },
  { handle: "marginsmall", displayName: "margin small", category: "traders" as const },
  { handle: "0x_Leo_", displayName: "Leo", category: "traders" as const },
  { handle: "larpalt", displayName: "o.o", category: "traders" as const },
  { handle: "0xRenaissance", displayName: "Renaissance", category: "traders" as const },
  { handle: "wafxles", displayName: "W", category: "traders" as const },
  { handle: "JW100x", displayName: "JW", category: "traders" as const },
  { handle: "dailybrd", displayName: "bread", category: "traders" as const },
  { handle: "X7H___", displayName: "H7", category: "traders" as const },
  // crypto
  { handle: "oxranga", displayName: "xranga", category: "crypto" as const },
  { handle: "0xDeejay", displayName: "DJ", category: "crypto" as const },
  { handle: "CottenIO", displayName: "Tim Cotten", category: "crypto" as const },
  { handle: "QwQiao", displayName: "qw", category: "crypto" as const },
  { handle: "satsdats", displayName: "satsdats", category: "crypto" as const },
  { handle: "tulipking", displayName: "Tulip King", category: "crypto" as const },
  { handle: "cobie", displayName: "Cobie", category: "crypto" as const },
  { handle: "0xsmac", displayName: "smac", category: "crypto" as const },
  { handle: "btceejay", displayName: "hen", category: "crypto" as const },
  { handle: "badenglishtea", displayName: "badenglishtea", category: "crypto" as const },
  { handle: "px_721", displayName: "px", category: "crypto" as const },
  { handle: "nosanityxbt", displayName: "nosanity", category: "crypto" as const },
  { handle: "0xcollagen", displayName: "Colla", category: "crypto" as const },
  { handle: "theunipcs", displayName: "Unipcs", category: "crypto" as const },
  { handle: "obsidian_cap", displayName: "obsidian", category: "crypto" as const },
  { handle: "foobiusV", displayName: "Foobius", category: "crypto" as const },
  { handle: "xbtcas", displayName: "xbtcas", category: "crypto" as const },
  { handle: "chameleon_jeff", displayName: "jeff.hl", category: "crypto" as const },
  { handle: "leftcurvemaxing", displayName: "lefty", category: "crypto" as const },
  { handle: "crypticd22", displayName: "crypticd", category: "crypto" as const },
  { handle: "0xIT4I", displayName: "IT4I", category: "crypto" as const },
  { handle: "gumsays", displayName: "gum", category: "crypto" as const },
  { handle: "blackwidowbtc", displayName: "blackwidow", category: "crypto" as const },
  { handle: "0xdetweiler", displayName: "Theo", category: "crypto" as const },
  { handle: "wronguser000", displayName: "WRONGUSER", category: "crypto" as const },
  { handle: "based16z", displayName: "based16z", category: "crypto" as const },
  { handle: "defi_monk", displayName: "MONK", category: "crypto" as const },
  { handle: "chjokka", displayName: "chjokka", category: "crypto" as const },
  { handle: "bitmine", displayName: "thorfinn", category: "crypto" as const },
  { handle: "ThinkingUSD", displayName: "Flood", category: "crypto" as const },
  // onchain
  { handle: "0xHeme", displayName: "Heme", category: "onchain" as const },
  { handle: "0xENAS", displayName: "Eugene Ng Ah Sio", category: "onchain" as const },
  { handle: "MoneyPrinter0x", displayName: "MP", category: "onchain" as const },
  { handle: "0xSleuth_", displayName: "mcSleuth", category: "onchain" as const },
  // tradfi
  { handle: "abcampbell", displayName: "Campbell", category: "tradfi" as const },
  { handle: "MacroCRG", displayName: "CRG", category: "tradfi" as const },
  { handle: "alpinestar17", displayName: "Alpinestar", category: "tradfi" as const },
  { handle: "BobLoukas", displayName: "Bob Loukas", category: "tradfi" as const },
  { handle: "David_Grid", displayName: "David Grider", category: "tradfi" as const },
  { handle: "MelMattison1", displayName: "Mel Mattison", category: "tradfi" as const },
  { handle: "qthomp", displayName: "Quinn Thompson", category: "tradfi" as const },
  { handle: "ezcontra", displayName: "contra", category: "tradfi" as const },
  { handle: "ZeMirch", displayName: "Pepper", category: "tradfi" as const },
  { handle: "lazyvillager1", displayName: "The Giver", category: "tradfi" as const },
  { handle: "FloodCapital", displayName: "Duncan", category: "tradfi" as const },
  { handle: "bitcoindata21", displayName: "quantdata21", category: "tradfi" as const },
  // thematic
  { handle: "worldsfacing", displayName: "facing worlds", category: "thematic" as const },
  { handle: "optimist", displayName: "optimist", category: "thematic" as const },
  { handle: "ParidaGroup", displayName: "PP", category: "thematic" as const },
  { handle: "RHouseResearch", displayName: "Rittenhouse Research", category: "thematic" as const },
  { handle: "cburniske", displayName: "Chris Burniske", category: "thematic" as const },
  { handle: "molesy39", displayName: "Molesy", category: "thematic" as const },
  { handle: "izebel_eth", displayName: "jez", category: "thematic" as const },
  { handle: "Wild_Randomness", displayName: "Mandelbrot", category: "thematic" as const },
  { handle: "BowTiedLobster", displayName: "Lobster", category: "thematic" as const },
  { handle: "Citrini7", displayName: "Citrini", category: "thematic" as const },
  { handle: "HumaCapital", displayName: "Huma", category: "thematic" as const },
  { handle: "that1618guy", displayName: "that1618guy", category: "thematic" as const },
  { handle: "fejau_inc", displayName: "fejau", category: "thematic" as const },
  { handle: "GermeyAce", displayName: "Germey", category: "thematic" as const },
  { handle: "cryptoklotz", displayName: "doug funnie", category: "thematic" as const },
]

async function main() {
  for (const account of accounts) {
    await prisma.twitterAccount.upsert({
      where: { handle: account.handle },
      update: {},
      create: account,
    })
    console.log(`Seeded @${account.handle}`)
  }
  console.log(`\nDone. Seeded ${accounts.length} accounts.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
