import { PrismaClient } from "@prisma/client"
import { config } from "dotenv"

config({ path: ".env.local" })

const prisma = new PrismaClient()

type Account = {
  handle: string
  displayName: string
  categories: string[]
}

const accounts: Account[] = [
  { handle: "plur_daddy", displayName: "plur daddy", categories: ["traders", "thematic"] },
  { handle: "TraderNoah", displayName: "Noah", categories: ["vc"] },
  { handle: "lBattleRhino", displayName: "Rhino", categories: ["traders", "crypto"] },
  { handle: "HsakaTrades", displayName: "Hsaka", categories: ["crypto"] },
  { handle: "Pickle_cRypto", displayName: "pickle", categories: ["traders", "crypto", "onchain"] },
  { handle: "Bluntz_Capital", displayName: "Bluntz", categories: ["traders"] },
  { handle: "mel_8686", displayName: "Mel", categories: ["traders", "crypto"] },
  { handle: "avotoast", displayName: "Avocado Toast", categories: ["crypto", "onchain"] },
  { handle: "thoughtfultrade", displayName: "clairvoyant", categories: ["crypto", "traders", "thematic"] },
  { handle: "notwashed", displayName: "washed", categories: ["onchain"] },
  { handle: "gammichan", displayName: "Gammichan", categories: ["crypto", "onchain"] },
  { handle: "c2mtrading", displayName: "C2M", categories: ["traders", "crypto"] },
  { handle: "slipsliderr", displayName: "Puffy", categories: ["crypto"] },
  { handle: "0xn4te", displayName: "NATE", categories: ["crypto"] },
  { handle: "lightcrypto", displayName: "light", categories: ["traders", "crypto"] },
  { handle: "DonAlt", displayName: "DonAlt", categories: ["traders", "crypto"] },
  { handle: "crymeaCOIN", displayName: "pc", categories: ["crypto"] },
  { handle: "moneywithcarter", displayName: "Carter", categories: ["crypto"] },
  { handle: "koningkarell", displayName: "Koning", categories: ["traders", "crypto"] },
  { handle: "0xPajke", displayName: "Pajke", categories: ["traders", "crypto"] },
  { handle: "__bleeker", displayName: "bleeker", categories: ["traders", "crypto", "onchain"] },
  { handle: "ReetikaTrades", displayName: "Reetika", categories: ["traders", "crypto"] },
  { handle: "stoicsavage", displayName: "sto", categories: ["traders", "crypto"] },
  { handle: "docXBT", displayName: "Doc", categories: ["traders", "crypto"] },
  { handle: "Tradermayne", displayName: "Mayne", categories: ["traders", "crypto"] },
  { handle: "cointradernik", displayName: "Nik", categories: ["crypto", "traders"] },
  { handle: "22loops", displayName: "Looposhi", categories: ["crypto"] },
  { handle: "CryptoParadyme", displayName: "Dyme", categories: ["crypto", "traders"] },
  { handle: "ImTrizzy", displayName: "Trizzy", categories: ["traders", "crypto"] },
  { handle: "buyerofponzi", displayName: "Ponzi Trader", categories: ["traders", "crypto"] },
  { handle: "owen1v9", displayName: "owen", categories: ["traders", "crypto"] },
  { handle: "blknoiz06", displayName: "Ansem", categories: ["crypto"] },
  { handle: "d_gilz", displayName: "David", categories: ["traders", "crypto"] },
  { handle: "Ritesh_Trades", displayName: "Ritesh", categories: ["traders", "crypto"] },
  { handle: "c0xswain", displayName: "ML", categories: ["onchain", "crypto"] },
  { handle: "Rob100x", displayName: "Rob", categories: ["crypto", "onchain", "traders"] },
  { handle: "RiffRaffOz", displayName: "RiffRaff", categories: ["traders", "crypto"] },
  { handle: "Crypto_Chase", displayName: "Crypto Chase", categories: ["traders", "crypto"] },
  { handle: "0xuberM", displayName: "uberM", categories: ["onchain"] },
  { handle: "xauchasing", displayName: "xauChasing", categories: ["traders", "crypto"] },
  { handle: "iamnotmagi", displayName: "Magi", categories: ["onchain"] },
  { handle: "Redactedpupil", displayName: "boop", categories: ["crypto"] },
  { handle: "ryzzqq", displayName: "Risk", categories: ["crypto", "traders"] },
  { handle: "BigTrout300", displayName: "BigTrout", categories: ["crypto", "traders", "tradfi"] },
  { handle: "Cassh0rt", displayName: "Cassh0rt", categories: ["crypto", "traders"] },
  { handle: "Cheshire_Cap", displayName: "Cheshire Capital", categories: ["traders", "crypto"] },
  { handle: "0xSunRun", displayName: "SunRun", categories: ["crypto"] },
  { handle: "issathecooker", displayName: "Issa", categories: ["onchain"] },
  { handle: "soulessmetanoia", displayName: "souless", categories: ["crypto", "traders"] },
  { handle: "retro", displayName: "retro", categories: ["crypto", "onchain"] },
  { handle: "real_y22", displayName: "Y22", categories: ["traders", "crypto"] },
  { handle: "onevsnine", displayName: "1v9", categories: ["crypto"] },
  { handle: "effervescence_o", displayName: "effervescence", categories: ["traders", "crypto"] },
  { handle: "bagsheera", displayName: "bags", categories: ["crypto", "traders"] },
  { handle: "sized_in", displayName: "sized in", categories: ["onchain"] },
  { handle: "Parida", displayName: "Parida", categories: ["traders", "crypto"] },
  { handle: "goosexyz_", displayName: "Goose", categories: ["onchain"] },
  { handle: "PlutonicXBT", displayName: "Snorlax", categories: ["crypto"] },
  { handle: "Erasing_Light", displayName: "Dystopia", categories: ["crypto", "traders"] },
  { handle: "insomniacxbt", displayName: "insomniac", categories: ["traders", "crypto", "tradfi"] },
  { handle: "CavanXy", displayName: "Cav", categories: ["traders", "crypto"] },
  { handle: "QuantMeta", displayName: "Metaquant", categories: ["crypto", "traders"] },
  { handle: "stogolp", displayName: "sgp", categories: ["crypto", "traders"] },
  { handle: "Web3Quant", displayName: "W3Q", categories: ["traders", "crypto"] },
  { handle: "0xMentalIllness", displayName: "Dumpelstiltskin", categories: ["tradfi"] },
  { handle: "0xLawliette", displayName: "L", categories: ["onchain"] },
  { handle: "0xfhd_", displayName: "fhd", categories: ["onchain"] },
  { handle: "GCRClassic", displayName: "GCR", categories: ["traders", "crypto"] },
  { handle: "chumbawamba22", displayName: "Chumbawamba", categories: ["traders", "crypto", "tradfi"] },
  { handle: "yeezytwts", displayName: "yeezy", categories: ["crypto"] },
  { handle: "GiganticRebirth", displayName: "GCR (journal)", categories: ["traders", "crypto"] },
  { handle: "conzimp", displayName: "Ansem (journal)", categories: ["crypto"] },
  { handle: "spyzer", displayName: "spyzer", categories: ["onchain"] },
  { handle: "awawat", displayName: "Awawat", categories: ["traders", "crypto"] },
  { handle: "cryptojamie7", displayName: "CryptoJamie", categories: ["crypto", "onchain"] },
  { handle: "blockgraze", displayName: "blockgraze", categories: ["crypto"] },
  { handle: "comfortablylong", displayName: "spiro", categories: ["crypto", "traders"] },
  { handle: "PaikCapital", displayName: "hdf", categories: ["traders", "crypto", "tradfi"] },
  { handle: "Juicycooks", displayName: "juicy", categories: ["onchain"] },
  { handle: "kelxyz_", displayName: "kel", categories: ["crypto", "thematic"] },
  { handle: "TruckPump", displayName: "Pump Truck", categories: ["traders", "crypto"] },
  { handle: "Pentosh1", displayName: "Pentoshi", categories: ["crypto"] },
  { handle: "skytrades8", displayName: "Sky", categories: ["traders", "crypto"] },
  { handle: "dogoshii", displayName: "dogo was here", categories: ["onchain"] },
  { handle: "degentradingLSD", displayName: "degentrading", categories: ["traders", "crypto", "tradfi"] },
  { handle: "mustached0", displayName: "mustached0", categories: ["onchain"] },
  { handle: "coin_casanova", displayName: "casa", categories: ["crypto"] },
  { handle: "levels_crypto", displayName: "levels", categories: ["onchain"] },
  { handle: "TheCryptoNexus", displayName: "Nexus", categories: ["traders", "crypto"] },
  { handle: "tetra_gamma", displayName: "tetra gamma", categories: ["crypto", "traders"] },
  { handle: "rodeo_crypro", displayName: "Rodeo", categories: ["onchain", "crypto"] },
  { handle: "whodoneit21", displayName: "whodoneit21", categories: ["onchain"] },
  { handle: "Erebos991", displayName: "Erebos", categories: ["traders", "crypto"] },
  { handle: "0xSisyphus", displayName: "Sisyphus", categories: ["crypto"] },
  { handle: "smileycapital", displayName: ":)", categories: ["traders", "crypto"] },
  { handle: "punter_punts", displayName: "punter", categories: ["onchain", "crypto"] },
  { handle: "Opaque1555", displayName: "Opaque", categories: ["onchain"] },
  { handle: "0xfattyfrog", displayName: "fattyfrog", categories: ["crypto", "traders"] },
  { handle: "game_for_one", displayName: "Game", categories: ["onchain"] },
  { handle: "Nstr_tj", displayName: "tj", categories: ["traders", "crypto"] },
  { handle: "profitmaxxing", displayName: "magi", categories: ["onchain"] },
  { handle: "marginsmall", displayName: "margin small", categories: ["onchain"] },
  { handle: "0x_Leo_", displayName: "Leo", categories: ["onchain"] },
  { handle: "larpalt", displayName: "o.o", categories: ["onchain"] },
  { handle: "0xRenaissance", displayName: "Renaissance", categories: ["onchain"] },
  { handle: "wafxles", displayName: "W", categories: ["traders", "crypto"] },
  { handle: "JW100x", displayName: "JW", categories: ["onchain"] },
  { handle: "dailybrd", displayName: "bread", categories: ["crypto", "traders", "onchain", "tradfi"] },
  { handle: "X7H___", displayName: "H7", categories: ["crypto"] },
  { handle: "oxranga", displayName: "xranga", categories: ["builders"] },
  { handle: "0xDeejay", displayName: "DJ", categories: ["crypto"] },
  { handle: "CottenIO", displayName: "Tim Cotten", categories: ["builders"] },
  { handle: "QwQiao", displayName: "qw", categories: ["crypto", "vc"] },
  { handle: "satsdats", displayName: "satsdats", categories: ["onchain"] },
  { handle: "tulipking", displayName: "Tulip King", categories: ["crypto", "onchain", "thematic"] },
  { handle: "cobie", displayName: "Cobie", categories: ["crypto"] },
  { handle: "0xsmac", displayName: "smac", categories: ["crypto", "traders", "vc", "thematic"] },
  { handle: "btceejay", displayName: "hen", categories: ["crypto", "traders"] },
  { handle: "px_721", displayName: "px", categories: ["onchain"] },
  { handle: "nosanityxbt", displayName: "nosanity", categories: ["onchain"] },
  { handle: "0xcollagen", displayName: "Colla", categories: ["crypto"] },
  { handle: "obsidian_cap", displayName: "obsidian", categories: ["crypto"] },
  { handle: "foobiusV", displayName: "Foobius", categories: ["onchain"] },
  { handle: "xbtcas", displayName: "xbtcas", categories: ["crypto", "traders", "onchain"] },
  { handle: "chameleon_jeff", displayName: "jeff.hl", categories: ["builders"] },
  { handle: "crypticd22", displayName: "crypticd", categories: ["onchain"] },
  { handle: "0xIT4I", displayName: "IT4I", categories: ["crypto"] },
  { handle: "blackwidowbtc", displayName: "blackwidow", categories: ["traders", "crypto"] },
  { handle: "0xdetweiler", displayName: "Theo", categories: ["onchain"] },
  { handle: "wronguser000", displayName: "WRONGUSER", categories: ["traders", "crypto", "onchain"] },
  { handle: "based16z", displayName: "based16z", categories: ["traders", "crypto", "tradfi"] },
  { handle: "defi_monk", displayName: "MONK", categories: ["vc"] },
  { handle: "chjokka", displayName: "chjokka", categories: ["onchain"] },
  { handle: "bitmine", displayName: "thorfinn", categories: ["onchain"] },
  { handle: "ThinkingUSD", displayName: "Flood", categories: ["crypto", "traders"] },
  { handle: "0xHeme", displayName: "Heme", categories: ["onchain"] },
  { handle: "0xENAS", displayName: "Eugene Ng Ah Sio", categories: ["crypto", "traders"] },
  { handle: "MoneyPrinter0x", displayName: "MP", categories: ["crypto", "traders", "tradfi", "thematic"] },
  { handle: "0xSleuth_", displayName: "mcSleuth", categories: ["onchain"] },
  { handle: "abcampbell", displayName: "Campbell", categories: ["tradfi"] },
  { handle: "alpinestar17", displayName: "Alpinestar", categories: ["onchain"] },
  { handle: "BobLoukas", displayName: "Bob Loukas", categories: ["traders", "crypto"] },
  { handle: "David_Grid", displayName: "David Grider", categories: ["crypto", "traders", "vc"] },
  { handle: "MelMattison1", displayName: "Mel Mattison", categories: ["traders", "tradfi"] },
  { handle: "qthomp", displayName: "Quinn Thompson", categories: ["tradfi"] },
  { handle: "ezcontra", displayName: "contra", categories: ["traders", "crypto", "tradfi"] },
  { handle: "lazyvillager1", displayName: "The Giver", categories: ["crypto", "traders", "thematic"] },
  { handle: "FloodCapital", displayName: "Duncan", categories: ["crypto", "traders"] },
  { handle: "bitcoindata21", displayName: "quantdata21", categories: ["crypto"] },
  { handle: "optimist", displayName: "optimist", categories: ["onchain"] },
  { handle: "ParidaGroup", displayName: "PP", categories: ["crypto", "traders"] },
  { handle: "RHouseResearch", displayName: "Rittenhouse Research", categories: ["tradfi"] },
  { handle: "cburniske", displayName: "Chris Burniske", categories: ["crypto", "vc"] },
  { handle: "molesy39", displayName: "Molesy", categories: ["crypto"] },
  { handle: "izebel_eth", displayName: "jez", categories: ["traders", "crypto"] },
  { handle: "Wild_Randomness", displayName: "Mandelbrot", categories: ["traders", "crypto", "tradfi"] },
  { handle: "BowTiedLobster", displayName: "Lobster", categories: ["tradfi"] },
  { handle: "Citrini7", displayName: "Citrini", categories: ["tradfi"] },
  { handle: "HumaCapital", displayName: "Huma", categories: ["crypto", "traders"] },
  { handle: "that1618guy", displayName: "that1618guy", categories: ["crypto", "traders"] },
  { handle: "fejau_inc", displayName: "fejau", categories: ["traders", "crypto", "tradfi", "thematic"] },
  { handle: "GermeyAce", displayName: "Germey", categories: ["builders"] },
  { handle: "0xDeployer", displayName: "0xDeployer", categories: ["builders"] },
]

async function main() {
  for (const account of accounts) {
    await prisma.twitterAccount.upsert({
      where: { handle: account.handle },
      update: { categories: account.categories },
      create: account,
    })
    console.log(`Seeded @${account.handle}`)
  }
  console.log(`\nDone. Seeded ${accounts.length} accounts.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
